# Generated by Django 5.0.7 on 2024-08-07 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='membership',
            field=models.CharField(choices=[('B', 'BRONZE'), ('S', 'SILVER'), ('G', 'GOLD')], default='B', max_length=1, verbose_name='Статус'),
        ),
    ]
